### ISSUE TITLE
All (both) validation libraries required to pass TypeScript checks

### ISSUE THREAD

**Issue by jangerhofer** [airjp73/remix-validated-form#13]
Hello, there!

I noticed that the library export barreling which ultimately lands in `node_modules/remix-validated-form/build/index.d.ts` will cause a type-checking error when one of the validation libraries is missing.  For instance, with `zod` installed but `yup` not installed, I get:

```bash
node_modules/remix-validated-form/build/validation/withYup.d.ts:1:49 - error TS2307: Cannot find module 'yup' or its corresponding type declarations.

1 import type { AnyObjectSchema, InferType } from "yup";
                                                  ~~~~~
Found 1 error.
```

...even when I only use `zod` schemas in my application.
______

I threw together a quick reproduction [here](https://github.com/jangerhofer/remix-validated-form-yup-type-error-repro).  Just run `npm i && npm run typecheck`!

Workarounds are straightforward enough -- ranging from just installing both validation libraries (`remix-validated-form` is just importing types from the validation library anyway!) to configuring TypeScript to ignore this error from its particular source -- but I figure it would be nice to avoid the type error when possible.

If I am not mistaken, the conventional mechanism to let the library user choose a 'plugin' is to avoid re-exporting the contents of the peer dependency modules (`yup`/`zod`) from the common, `index` file.  Instead, users import the dependency-agnostic parts of the library from the `index` barrel.  The dependency-dependent parts (`withYup`/`withZod`) are then imported from a more specific path (e.g. right now that is `remix-validated-form/build/validation/withYup`).

Would a change like that make sense?

**Comment by airjp73** [comment]
Thanks for the issue! This is definitely something I want to fix. I'm kicking myself a bit that I didn't test it more thoroughly 🤦.

Since this will be a breaking change, I wonder if it makes sense to break them out into separate packages. I already have this organized as a monorepo so the lift shouldn't be _that_ bad. Not 100% sure how to organize the validator tests in that case but that can be figured out.

Or, if there's a way to fix this without a breaking change, we should do that, but it seems like there's no way around that when removing/moving an export?

I could play around with this after work today -- unless you wanted to take a swing at it?

**Comment by airjp73** [comment]
I have this working locally and will probably merge it in tonight or tomorrow.

**Comment by jangerhofer** [comment]
Amazing -- you beat me to the punch! :)

>  I'm kicking myself a bit that I didn't test it more thoroughly

Hah, I only caught it after my CI `tsc` job failed with an error from the `remix-validated-form` barrel, so I would label this an obscure error.

> no way around that when removing/moving an export

I agree that there is certainly no practical way -- the new major version makes perfect sense.
