### ISSUE TITLE
[Bug]: zod-form-data does not support arrays of objects

### ISSUE THREAD

**Issue by JeffBeltran** [airjp73/remix-validated-form#133]
### Which packages are impacted?

- [ ] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [X] `zod-form-data`

### What version of these packages are you using?

- `"@remix-validated-form/with-zod": "^2.0.1"`
- `"remix-validated-form": "^4.5.0"`
- `"zod": "^3.17.3"`
- `"zod-form-data": "^1.2.0"`

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/affectionate-benji-lg6bek?file=/app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. create nested form
2. submit nested form

### Expected behavior

when submitting a nested form expect to see an array of those items

### Platform

- OS: macOS
- Browser: Chrome

### Additional context

included in the reproduction, i have a work around flag that uses the `remix-validated-form` package and that does what i would expect.

See https://github.com/airjp73/remix-validated-form/discussions/129 for similar details

**Comment by airjp73** [comment]
Copying my response from there. I think this would be a good issue for someone to tackle if they were interested in contributing. I should be able to fix in the next week or so if nobody does it first (almost done unpacking 😆 )

The issue is this line [here](https://github.com/airjp73/remix-validated-form/blob/main/packages/zod-form-data/src/helpers.ts#L170) should be using `set` from lodash.

**Comment by JeffBeltran** [comment]
@airjp73 funny enough i just got back to looking at this again and was working on this fix, i'll push up a PR in a bit

**Comment by airjp73** [comment]
Fix published in zod-form-data v1.2.1
