### ISSUE TITLE
[Feature]: zfd supports esm module

### ISSUE THREAD

**Issue by lulucas** [airjp73/remix-validated-form#141]
### What is the new or updated feature that you are suggesting?

When I build my project which ```"type": "module"```

```
import { zfd as zfd$1 } from "zod-form-data";
         ^^^
SyntaxError: Named export 'zfd' not found. The requested module 'zod-form-data' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:    

import pkg from 'zod-form-data';
const { zfd: zfd$1 } = pkg;
```

### Why should this feature be included?

Support esm module import.

**Comment by airjp73** [comment]
Hi! Do you have a repo or codesandbox with a reproduction? `zod-form-data` [_should_ have an esm output](https://github.com/airjp73/remix-validated-form/blob/main/packages/zod-form-data/package.json#L6). It's entirely possible I've set it up wrong, though.

**Comment by airjp73** [comment]
This might be a sveltekit issue, rather than zfd. I found a stackoverflow [here](https://stackoverflow.com/questions/72682047/sveltekit-importing-esm-package-produces-errors-that-works-with-vite) of someone having the same problem. Like they mention there, zfd appears to work with plain vite, but not when running sveltekit build.
