### ISSUE TITLE
[Bug]: A component is changing an uncontrolled input to be controlled. + controlled field validation not working 

### ISSUE THREAD

**Issue by piotrkulpinski** [airjp73/remix-validated-form#185]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

"remix-validated-form": "^4.5.7",
"@remix-validated-form/with-yup": "^2.0.1",

### Please provide a link to a minimal reproduction of the issue.

https://stackblitz.com/edit/node-cb9mfk?file=app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Enter some value into the name field
2. Open the console to see the issue
3. Try submitting empty values
4. Add a 3-char value to the name field and submit again
5. See slug error not updating 

### Expected behavior

I expect to be able to edit the value of the controlled field with another one and keep its validation working.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [106.0]

**Comment by airjp73** [comment]
Hi!

There are a couple separate issues here.

### Changing from uncontrolled to controlled

This is a common error message with forms in React. The reason is that `useControlledField` has no default value. React sees the `value` is undefined to start which React interprets as the input being uncontrolled. When you set a value, now the input is controlled. To fix, you just have to add a default value for `slug`.

```
<ValidatedForm defaultValues={{ slug: '' }}
// etc
```

### Validation not updating

By default, a field doesn't get validated when another field changes. There's an issue already to improve this (#182), so I'm going to close this ticket in favor of that ticket.

You can fix this in your form by using [validateField](https://www.remix-validated-form.io/reference/use-form-context#validateField) in your change handler like this:

```
const handleChange = (e: ChangeEvent<HTMLInputElement>): void => {
  setSlug(encodeURI(e.target.value.toLowerCase()));
  validateField('slug');
};
```
