### ISSUE TITLE
[Feature]: Support for projects using the new react-router (the remix one)

### ISSUE THREAD

**Issue by luispuig** [airjp73/remix-validated-form#206]
### What is the new or updated feature that you are suggesting?

The option of using this library in projects using the new remix router but outside of remix.

AFAIK the problem is the imports using `{useActionData, useMatches, useTransition} from @remix-run/react`, instead of `{useActionData, useMatches, useNavigation} from react-router-dom`.

I think that useNavigation has the same interface as useTransition. I am not sure what the name was changed.

### Why should this feature be included?

It will expand the possibilities of the library

**Comment by airjp73** [comment]
Yeah, this would definitely be nice to have. I'd love to have some help looking into this -- not sure how much time I have to really get this done.

**Comment by luispuig** [comment]
I will fork it and modify the imports to check if it works as expected. If it does we can figure out how to expose an option to decide the mode and manage the imports.

We are working on a none-remix project that potentially will be migrated to Remix, so we are keeping the remix flavour as much as possible. For instance, we are using https://github.com/vjee/vite-plugin-remix-routes to use the same filesystem routing.

**Comment by luispuig** [comment]
I gave it a try today but I think I am doing something wrong.

- Changed the imports in internal/hooks
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/24297787/201329323-9d0bf09a-11fa-45b2-892b-bb494505bbc4.png">

- Changed ValidatedForm
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/24297787/201329364-3482bfc3-d826-49bb-b1cf-d168aebf9287.png">

- Changed the package.json
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/24297787/201329412-201ac834-e03f-4d0a-acaf-1bec5be95b0f.png">


I added a very simple example with the new data-router: https://reactrouter.com/en/main/routers/create-browser-router#createbrowserrouter

Then, I am getting a very weird error:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/24297787/201329804-211aca99-717c-43d0-93f2-b2da223461dd.png">

It seems to happen when the useErrorResponseForForm hook is trying to use the useActionData hook. At first, I thought it was a problem with the peer dependency, then I tried "sharing" the hooks using a global variable on window, but I got the same error. Finally, I start commenting code in the hook and ValidatedForm and I was getting exactly the same error, pointing to a line that is commented. So, I am probably setting wrongly the dev environment or something.

**Comment by zainfathoni** [comment]
I'm looking forward to this issue being fixed, too.

Currently, I'm stuck due to this error.
https://app.warp.dev/block/o0kptGdA16aXIv9SwXxA3h

**Comment by aaronadamsCA** [comment]
With a few API changes, I think I can see how the next major version of this library could work with both React Router and Remix.

As a very large bonus, I think it would also work outside Remix; my own goal is to build validated forms in our UI component library so we can develop and test our Remix app's forms using Storybook.

Here is my basic idea:

- Require users to wrap their app with a new `<ValidatedFormProvider value={{ useFetcher }}>`. Leave it up to them whether to import `useFetcher` from React Router or Remix.
  - Now you don't need Remix imports `Form`, `useSubmit`, and `useTransition` anymore, since you can always access `fetcher.Form`, `fetcher.submit`, and `fetcher.state`.
  - In Storybook, I believe we could just mock a `fetcher` that turns each valid form submission into a Storybook action.
- Remove server API [`setFormDefaults`](https://www.remix-validated-form.io/reference/set-form-defaults#setFormDefaults). Users can already pass `defaultValues` as a `ValidatedForm` prop.
  - Now you don't need Remix import `useMatches` anymore.
- Remove server API [`validationError`](https://www.remix-validated-form.io/reference/validation-error#validationError). Users should instead pass `errors` (required) and `submittedData` (optional) as `ValidatedForm` props.
  - Now you don't need Remix import `useActionData` anymore.

This approach adds a `ValidatedFormProvider` installation step, and eliminates "magic" Remix server APIs. But as far as I can tell, it would deliver React Router compatibility; it should also allow for substantial improvements to code safety, since you'd now be able to typecheck `errors` and `submittedData` to make sure they match `validator`.

Plus the aforementioned Storybook compatibility.

I might be missing something, but maybe this idea could at least serve to move the discussion forward!

**Comment by airjp73** [comment]
An approach I've been thinking about off and on would be to go with a "core" package + adapter type pattern. I personally really like the `validationError` api, but that could live in a remix-specific adapter. I'm also wondering, if we broke down the `ValidatedForm` further, is there potential to be usable in Next.js as well? I haven't used Next.js in a long time, but I've heard their server actions & forms have some similarities to how remix does them.

**Comment by aaronadamsCA** [comment]
Agreed that a core + adapter pattern would be good as well.

I see no reason this library can't be framework-agnostic. IMHO my least favourite parts of it today are also the only parts that currently bind it to the Remix server:

1. Tight coupling to Remix `useActionData`.
   - I think `validationError` should just return data, not a response; and the user should be responsible for getting that data from `useActionData` to `ValidatedForm`. This is only a tiny amount of extra work, but it makes the API _so much more expressive_.
   - This is also framework-agnostic, since you no longer need to care how this data gets to the component.
   - Coincidentally it's also aligned with the apparent future of Remix, in which actions might no longer return responses: https://github.com/remix-run/remix/discussions/7640
2. Tight coupling to Remix `useMatches`.
   - I don't think a user actually needs `setFormDefaults` to help them get default values from a `loader` to `ValidatedForm`. This bit could simply move to the docs.
   - If absolutely necessary, a Remix adapter package could export a `useDefaultValuesFromMatches` hook without saddling the main library, whose value the user could then pass to `ValidatedForm`.

If you can make these changes, I _think_ you've abstracted away all of the server-to-client responsibilities of this library, which should get you most of the way there. I think the rest of it would just be little adapter libraries that inject the right dependencies, not unlike [Remix](https://github.com/remix-run/remix/blob/main/packages/remix-cloudflare/implementations.ts) [adapter](https://github.com/remix-run/remix/blob/main/packages/remix-deno/implementations.ts) [libraries](https://github.com/remix-run/remix/blob/main/packages/remix-node/implementations.ts).

As a nice side effect, these changes would actually help users learn Remix, in the same spirit as the API changes in MSW v2:

> https://mswjs.io/blog/introducing-msw-2.0
>
> From the practical standpoint, the `res()` composition API achieves its goals: it allows for response declaration, it’s readable, it scales and abstracts well. But years of shipping open-source software have taught me there are more aspects to your code than practicality. Despite its apparent benefits, this composition API failed to achieve a rather important characteristic.
>
> **It failed to educate.**
>
> The degree of abstraction in the `res()` function is far too high to teach you, the developer, anything about actual responses on the web. As a maintainer with thousands of projects depending on the software I build, I feel it’s my responsibility to care about what developers learn from that software. I want them to achieve their goals but I also want them to learn concepts and APIs they can apply even outside of MSW because I firmly believe that’s what a good software does.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

v6 has adopted the adapter pattern and can be used anywhere you use react (even Next.js if that's your thing).

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
