### ISSUE TITLE
[Feature]: FormState component to read component state + some feedback (Code solution included)

### ISSUE THREAD

**Issue by superjose** [airjp73/remix-validated-form#232]
### What is the new or updated feature that you are suggesting?

Hi airjp73 🤗.

First of all, thank you very much for this library! It has the nicest developer ergonomics in form flexibility from everything I've tried. 

I've been searching for a form library solution in Remix. I've tried remix-forms, remix-params-helper, vanilla Remix, react-hook-forms, and all it becomes extremely tricky when I want:

- Upload a file using a custom file uploader (E.g: I have an Avatar Upload. I crop the image and then upload it to the server)
- Use the form as a state manager. 
- Use deeply nested objects to create the form (Using zod objects).
- Array supports

All at the same time.

Working with **form state** is the only thing I've been struggling with in this library.  

For example, I wanted to read the value from radio buttons in another component. I ran into the `useControlField`'s limitation when using radio or checkbox buttons. It clashed as the name had to be the same in all radio inputs. 

The workaround was to manually set the radio value using a parent useControlField that updated both inputs.

I also wanted to read the form's current state to render elements conditionally. I've always loved how Formik allowed you to use childrenProps for that.

While I don't know the performance implications, I've created this small component to do that. It also infers from the Zod Schema  giving you autocomplete powers!

```FormState.tsx
import type { ReactNode } from "react";
import { useFormContext } from "remix-validated-form";
import type {
  infer as ZodInfer,
  SomeZodObject,
  ZodEffects,
  ZodTypeAny,
} from "zod";

type FormSchema<T extends ZodTypeAny = SomeZodObject | ZodEffects<any>> =
  | ZodEffects<T>
  | SomeZodObject;

type FormStateProps<Schema extends FormSchema> = {
  children: ((input: ZodInfer<Schema>) => ReactNode) | ReactNode;
};

export function FormState<Schema extends FormSchema>(
  props: FormStateProps<Schema>
) {
  const form = useFormContext();
  const values = JSON.stringify(
    Object.entries(form.getValues())
  ) as ZodInfer<Schema>;
  const { children } = props;
  return <>{typeof children === "function" ? children(values) : children}</>;
}
```

You use it like this:
```
   <ValidatedForm
      encType="multipart/form-data"
      validator={userProfileUpsertValidator}
      method="post"
      defaultValues={defaultValues}
      id="js-validated-form"
    >
      <FormState<typeof userProfileCreateSchema>>
        {(values) => (
          {/* Now you can do whatever you want with the values, like conditional rendering or creating a wizard*/}
       )
     </FormState>
```

Where:

`userProfileCreateSchema` is your `zod.object()` and `userProfileUpsertValidator` is `userProfileUpsertValidator = withZod(userProfileCreateSchema)`;

### Why should this feature be included?

It allows you to use `remix-validated-form` as a state manager, allowing conditional rendering without reimplementing components.

**Comment by airjp73** [comment]
Hi! Thanks for taking the time to bring this up. Unfortunately, the `FormState` approach you outline here isn't really feasible. `getValues` isn't meant to be called in the render phase, and when I tried it I got an error during server rendering. This also won't reliably updated when the form values change. For `useControlField`, only components calling into `useControlField` will update when that value changes. For uncontrolled inputs, we don't even store the form values.

If you like the render props approach instead of using a hook, you can wrap `useControlledField` (or any other hook) like this:
```ts
const ControlledField = ({ name, children }) => {
  const [value, setValue] = useControlledField(name);
  return children(value, setValue);
}
```

I wrote up a quick demo / example on how you could approach writing a radio group and how you might tap into that value using `useControlField`.

https://stackblitz.com/edit/node-6ah8pk?file=app/routes/index.tsx

Another approach could be to write a `RadioGroup` component that uses `useControlField` and use bare `input` elements instead of calling `useField` for each input.

**Comment by mschipperheyn** [comment]
I implemented a similar component before finding this issue. The key issue I'm trying to solve is to debug current form values. Which should be easy and makes development hard if it's not. Perhaps there is a better way?
