### ISSUE TITLE
[Bug]: No way to prevent default behaviour of the parent form

### ISSUE THREAD

**Issue by piotrkulpinski** [airjp73/remix-validated-form#240]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [X] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

4.6.7

### Please provide a link to a minimal reproduction of the issue.

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

I intend to make certain fields editable via a "popup" portal, where the popup itself is managed by a form. When you "submit" the nested form, the field updates.

However, the onSubmit prop of the `ValidatedForm` won't prevent the parent form from submitting.

Here's my code:

```tsx
const onSubmit = async (data: any, e: FormEvent<HTMLFormElement>) => {
  e.preventDefault()
  e.stopPropagation()

  // Do something with data
}

return (
  <ValidatedForm
    validator={validator}
    defaultValues={defaultValues}
    onSubmit={onSubmit}
  >
	// Fields
  </ValidatedForm>
)
```

This is used as a component within another ValidatedForm. If I submit the popup form, it'll also submit the parent one. 

Is there a way to change that? Not sure if the asynchronous nature of the onSubmit function is the issue here. 

### Screenshots or Videos

-

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [105]

**Comment by piotrkulpinski** [comment]
It won't work even if the nested form is moved away to a separate DOM node using portals: 
![CleanShot 2023-02-03 at 10 52 04](https://user-images.githubusercontent.com/358412/216569342-86baccaa-1d8a-4be0-8226-3efa52ec2428.png)

**Comment by airjp73** [comment]
Yeah, this is definitely related to `onSubmit` being asynchronous. And unfortunately, I think the only way to actually fix this is in userland, not in this library.

Without portals I'm pretty sure you're not [supposed to nest form elements](https://stackoverflow.com/questions/555928/is-it-valid-to-have-a-html-form-inside-another-html-form/555970#555970).

With portals, this happens because React bubbles events up through the portal as though it was nested without a portal.

One thing you could do is listen to the submit event on another element in your popover and `stopPropagation` there. I do this a lot with click events to prevent clicks inside portals from bubbling up into unexpected places. Here's an example:

```
<div onSubmit={e => e.stopPropagation()}>
  <ValidatedForm {...etc} />
</div>
```

That said, I think it's unideal though that there's a `stopPropagation` on the event we provide and it doesn't do anything. I think we should:

* Tweak the type of the event we pass to `onSubmit` to deprecate `stopPropagation`.
* Remove `stopPropagation` in the next major version and throw an error if you try to call it.
* Even though this is technically a breaking change, we're not breaking any real use-cases since it doesn't do anything as-is.

For completeness, I've thought through a couple other ideas I don't like:

* We could _always_ stop propagation.
  * Having the submit event not bubble past the form could be unexpected behavior. It's also a breaking change.
* We could stop propagation then re-dispatch the event if you don't stop propagation in your onSubmit
  * This isn't good because it will result in two submit events in the capture phase

**Comment by piotrkulpinski** [comment]
Thanks @airjp73 

Your workaround fixed the issue!
