### ISSUE TITLE
With yup boolean/checkbox value is always true when set as default

### ISSUE THREAD

**Issue by rzmz** [airjp73/remix-validated-form#26]
Very nice library! I have found a minor issue.

I have the schema defined as follows:
```typescript
const LoginSchema = yup.object({
    email: yup
        .string()
        .required()
        .email(),
    password: yup.string().required(),
    rememberMe: yup.boolean().default(true),
});
```
And the field is (I actually use chakra-ui Switch input, but the same issue is when using plain `<input type="checkbox" />` tag):
```
<input type="checkbox" name="rememberMe" value="true" />
```
Now when I submit the form, rememberMe value in action function
 ```typescript
const result = LoginValidator.validate(formData);
const { email, password, rememberMe } = result.data;
```
 is always true, regardless of checked state. When I remove .default(true) from my schema, it works correctly. Remix's own formData.get returns correctly always so I am pretty sure the bug is from remix-validated-form.

**Comment by airjp73** [comment]
This is actually one of those situations where the HTML standard is weird and `remix` is forcing us to learn the standards. :)

When a checkbox is submitted, the value you get in the form data is either the `value` of the input (when the checkbox is true) or the checkbox field is omitted completely. In your case this means the value will either `"true"` or not there at all. If you don't include a `value` on the input, then it will be `"on"` when it's true. [MDN reference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#value)

So the reason you get `true` every time is because, when the checkbox is unchecked, yup is seeing that the field is not there and supplying the default. To fix the issue, you'll need to create a `yup` schema that expects this behavior.

I'm not sure what, if anything, we can do in this library to ease this pain point, but if you have any ideas, I'm open to hearing them!

**Comment by rzmz** [comment]
Thanks for the clarification. I come from react-hook-form and I guess there was some magic at play that allowed using booleans.
