### ISSUE TITLE
[Bug]: When a fetcher is supplied via the ValidatedForm, the non-js path stops working

### ISSUE THREAD

**Issue by meza** [airjp73/remix-validated-form#273]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- "remix-validated-form": "4.6.11",
- "zod": "3.21.4"
- "@remix-validated-form/with-zod": "2.0.5",

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/s/epic-saha-u99g03?file=/app/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Keep Javascript on
2. leave the input field empty
3. submit the form
4. see the validation work
5. Turn JS off
6. leave the input field empty
7. see the validation NOT work
8. remove the fetcher from the ValidatedForm props
9. submit an empty field
10. the validation works

### Expected behavior

I'd expect the validation to work with a custom fetcher

### Platform

Tried on win 11, latest firefox and chrome

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

Due to the extent of the rework in v6, I'm going to close this issue for now. If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
