### ISSUE TITLE
[Bug]: Default values are not refreshing properly

### ISSUE THREAD

**Issue by hernandcb** [airjp73/remix-validated-form#315]
### Which packages are impacted?

- [X] `remix-validated-form`
- [X] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

-  "remix-validated-form": "^4.6.9",
-  "@remix-validated-form/with-zod": "^2.0.5",
- "zod-form-data": "^2.0.0"

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/sandbox/validated-form-default-values-kjn5xk?file=%2Fapp%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

select "first" -> the values are loaded but the select does not change.
select "third" -> the select value is updated to "first"
select "second" -> all inputs are updated with the "third" values

### Expected behavior

As a user I expect the values received are set as default values correctly. However, when reloading the page the values shown are those from previous requests, not the latest one.

### Platform

- OS: [Linux]
- Browser: [Chrome]
- Version: [114]

### Additional context

First of all, thank for the great work with the library !

I'm using remix-validated-form to manage my form containing several input fields.

According to the change event on one select field I reload the route to get the values to fill in the form, which I pass as default values. However, the form is not setting those values properly.

Each time the route reloads the default values are those from the previous request, not the latest one. When I tested it using remix Form it works as expected.
You can also test how I expect it to work using the remix Form (there is a link below the form in the sandbox)

Is there something I'm not doing properly or it may be an issue with the library ?

**Comment by airjp73** [comment]
Thanks for the detailed reproduction! It looks like the observed behavior is a combination of a couple different issues.

1. `getInputProps` isn't setting the defaultValue of a `select` at all.

This will take some debugging to figure out, but it's definitely a problem.

2. Usage of `useField` is preventing the form values from fully switching over.

It seems like having `useField` in the page component is causing the form values to linger somehow, even after the form itself is reset. You can work around this by changing the id of the form every time you change the key.

This comes back to a pattern I keep seeing that I don't love, and that's using the ["use outside forms"](https://www.remix-validated-form.io/use-outside-forms) feature to use hooks in the component that renders the form. This inherently results in weird double updates because the `ValidatedForm` itself creates the form store. This is kinda my fault because it looks like that doc actually does this to demonstrate the functionality. The original intent of this feature was to support the fact that HTML forms allow inputs to be outside the form element itself, but has kind of evolved into a common pattern.

**Comment by cxreiff** [comment]
Not sure this has anything to do with the ["use outside forms"](https://www.remix-validated-form.io/use-outside-forms) pattern. I ran into the same issue just using this library exactly as described in the [integrate-your-components](https://www.remix-validated-form.io/integrate-your-components) section of the docs. Tried the suggestions of using resource-unique keys for the `key` and `id` form props, but even that fix was incomplete- while this caused it to reflect the correct data while navigating within the app, refreshing the page would always show the previous resource's data, somewhat bizarrely even if the *correct data* was being shown right before refreshing. Something is wrong with the way defaultValue is set.

**Comment by cxreiff** [comment]
Deepest apologies, MINUTES after posting this I discovered the issue, not directly related to `remix-validated-form`. For anyone running into similar problems, what you may actually be running into is browser autocomplete behavior overriding the default value immediately after the correct value is filled in! `autocomplete=off` on the form solved this issue in my case.

**Comment by airjp73** [comment]
RVF v6 has been released 🎉 

This should hopefully no longer be an issue in v6. If it's still a problem in that version, please feel free to open a new issue.

You can find the documentation [here](https://rvf-js.io) and the migration guide [here](https://rvf-js.io/migration).
