### ISSUE TITLE
[Bug]: checkbox must be a `boolean` type, but the final value was: `"on"`.

### ISSUE THREAD

**Issue by pullmann4rent** [airjp73/remix-validated-form#331]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

remix validate form 4.6.11

### Please provide a link to a minimal reproduction of the issue.

w

### Steps to Reproduce the Bug or Issue

I want to use a checkbox on my validate form but it is not working:

Got this error:

`checkbox must be a `boolean` type, but the final value was: `"on"`.`

### Expected behavior

```
const validator = withYup(
  yup.object({
    checkbox: yup.boolean().oneOf([true],'Message')
  })
);

<ValidatedForm method="post" validator={validator} className="form-booking">

<MyInputCheckbox name="checkbox" label="checkbox" defaultChecked={false} />

<MySubmitButton />

/ValidatedForm />
```

MyInputCheckbox
```
import { useField } from "remix-validated-form";

export const MyInputCheckbox = ({ name, className, value, ...props }: React.HTMLProps<HTMLInputElement>) => {
  const { error, getInputProps } = useField(name);
  return (
    <div>
      <input className={`${className} ${error && 'border-red'}`}  {...getInputProps({ type: "checkbox", value })} {...props} />
      {error && <p className="my-error-class">{error}</p>}
    </div>
  );
};
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by airjp73** [comment]
Hi! This is the expected behavior of an HTML checkbox ([MDN reference] (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox)). This library pulls data directly out of a FormData without checking the shape of the data.

The natural way to handle this case is to have your schema expect this and then transform the data to a boolean. (When the checkbox is unchecked there will be no value in the FormData for that field).
