### ISSUE TITLE
[Feature]: Provide an onSuccess property to the form

### ISSUE THREAD

**Issue by mrcwbr** [airjp73/remix-validated-form#350]
### What is the new or updated feature that you are suggesting?

I'd need a callback to show an alert or close a modal if a submit succeeds. e.g.:

```tsx
export async function action({ request }: ActionArgs) {
  const result = await validator.validate(
    await request.formData()
  );
  
  const {userName} = result.data

  if(!isUserNameTaken(userName)) {
    return validationError({
      fieldErrors: {
        userName: 'Username is already taken',
      },
    });
  }
  
  await createNewUser(userName);
  
  return true
}

export function MyRoute() {
  function onSuccess() {
    alert('Success!'); // or if the form is in a modal call onClose()
  }

  return (
    <ValidatedForm validator={validator} onSuccess={onSuccess}>
      <MyInput name="userName" />
      <MySubmitButton />
    </ValidatedForm>
  );
}
```

### Why should this feature be included?

currently the only workaround I found is to use a custom fetcher like this:

```tsx
export function MyRoute() {
  const fetcher = useFetcher();

  if (fetcher.data === true) {
    onSuccess();
    fetcher.data = undefined;
  }

  function onSuccess() {
    alert('Success!');  // or if the form is in a modal call onClose()
  }

  return (
    <ValidatedForm
      validator={validator}
      fetcher={fetcher}
    >
      <MyInput name="userName" />
      <MySubmitButton />
    </ValidatedForm>
  );
}
```

wouldn't it be a nice feature to provide a callback which is fired with the action's response-data if it's not an error?

**Comment by airjp73** [comment]
Unfortunately, not having an `onSuccess` callback was an intentional choice because it's a bit of a footgun.

For both the use-cases you called out, there are more natural ways to do it in Remix.

For toasts/alerts/etc, you can use [`session.flash`](https://remix.run/docs/en/main/utils/sessions#sessionflashkey-value).

For closing a modal, you might try having the modal open state rely on a query param and have your action return a `redirect` that removes the query param.

Anything more complex or specific than that, the solution would be the same as if you were using a plain Remix form.
