### ISSUE TITLE
[Bug]: setValue is not setting and validating transformed values in a useControlField input

### ISSUE THREAD

**Issue by bustawin** [airjp73/remix-validated-form#357]
### Which packages are impacted?

- [X] `remix-validated-form`
- [ ] `@remix-validated-form/with-zod`
- [ ] `@remix-validated-form/with-yup`
- [ ] `zod-form-data`

### What version of these packages are you using?

- `remix-validated-form`: `5.1.5`

### Please provide a link to a minimal reproduction of the issue.

https://codesandbox.io/p/devbox/charming-thunder-22r57g?file=%2Fapp%2Froutes%2Findex.tsx%3A32%2C3

### Steps to Reproduce the Bug or Issue

Use `useControlField<number>(name)` and `setValue` to manually set the value of an input inside a form. The twist is that we want to alter what the user typed, which in this case to keep it simple we just set the value to a constant "42" as a number:

```tsx
<input name={name} value={value || ""} onChange={(e) => setValue(42)} />
```

### Expected behavior

If we use a validation of
```typescript
const validator = withZod(
  z.object({
    name: z.number(),
  })
);
```
The validation should pass, but we still get an invalid form: `Expected number, received string`.

It feels that the library is still getting the value from the input directly, which is a string.

Moreover, if we remove the `name` of the input:
```tsx
<input value={value || ""} onChange={(e) => setValue(42)} />
```

We get a `Required` error from the validation.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Thanks for the library! I hope you can help me; thanks. :-)

**Comment by airjp73** [comment]
Hi! What your describing is working as intended. One of the core design decisions of this library is that the form itself is the source of truth for all the form data. So when we validate, we look directly at the form.

`useControlField` is analogous to just using `useState`. You can use it track and manipulate your form state, but it doesn't actually affect the data that comes out of the form.

To properly validate a number input, I'd recommend taking a look at `zod-form-data`'s [numeric](https://www.remix-validated-form.io/zod-form-data/api-reference#numeric) helper.

**Comment by mschipperheyn** [comment]
> `useControlField` is analogous to just using `useState`. You can use it track and manipulate your form state, but it doesn't actually affect the data that comes out of the form.

Ehh: WTF? For those of us stuck on 5.1.5 bc we can't afford a total refactor of our code base. I have a lot of code where we use `useControlField` to directly set values. After that I call `validate()` and often get stuck with 
```
Error: Validate called before form was initialized.
    at smartValidate (createFormStore.ts:116:11)
```

for no apparent reason. This is on children of a ValidateForm. 

Another issue we seem to have quite a bit seems related to the one you mention, that changes from `useControlField` `setX` calls don't seem to propagate to the form data and require a focus on another form field to trigger that change

**Comment by mschipperheyn** [comment]
My solution that worked to avoid the Validate issue, but which I don't understand why, is to add 
```
const [display, setDisplay] = React.useState<boolean>(false)
[...]
React.useEffect(() => {
   setDisplay(true)
}, [])

if(!display){ return null }

return <MyFormComponent />
```

**Comment by airjp73** [comment]
Hi!

What I mean by that is, just like if you do something like this:
```tsx
const [value, setValue] = useState("");

return (
  <div>
    <button onClick={() => setValue("changed!")>Change</button>
    <input value={value} />
  </div>
)
```

`setValue` doesn't immediately update the `value` of the input. You have to wait for React to rerender first, _then_ the input will have the correct value. Since RVF v5 exclusively uses only the form data available in the DOM to validate and submit, the FormData doesn't have the updated value from `setValue` until the `useControlledField` hook causes a rerender and React propagates the update to the DOM.

> For those of us stuck on 5.1.5

Migration is definitely a pain. If it helps, the names of the v6 packages changed, so it should be possible to install it alongside v5 and start using it in new code without migrating old code.

> After that I call validate() and often get stuck with
> 
> ```
> Error: Validate called before form was initialized.
>     at smartValidate (createFormStore.ts:116:11)
> ```
> 
> for no apparent reason. This is on children of a ValidateForm.

When I've seen this reported in the past it was because `validate` was being called in an effect or something on mount, which is usually the result of some kind of anti-pattern. But this behavior is definitely problematic and was one of the big motivators behind the v6 rewrite. It happens due to architectural decisions made in v1 that are no longer present in v6.
