### ISSUE TITLE
[Feature]: Alter DefaultValues typing to allow nulls

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [airjp73/remix-validated-form#68]
### What is the new or updated feature that you are suggesting?

New

### Why should this feature be included?

For most DB's empty fields are stored as null values, which technically doesn't meet the `defaultValues?: Partial<DataType>;` typing. 

I've been bypassing this by just running the objects through a `nullsToUndefined` function which works so this isn't an urgent thing, just a nice to have.

```tsx
type RecursivelyReplaceNullWithUndefined<T> = T extends null
  ? undefined
  : T extends Date
  ? T
  : {
      [K in keyof T]: T[K] extends (infer U)[]
        ? RecursivelyReplaceNullWithUndefined<U>[]
        : RecursivelyReplaceNullWithUndefined<T[K]>;
    };

export function nullsToUndefined<T>(obj?: T): RecursivelyReplaceNullWithUndefined<T> {
  if (obj === null || obj === undefined) {
    return undefined as any;
  }

  // object check based on: https://stackoverflow.com/a/51458052/6489012
  //@ts-ignore
  if (obj.constructor.name === "Object") {
    for (let key in obj) {
      obj[key] = nullsToUndefined(obj[key]) as any;
    }
  }
  return obj as any;
}
```

**Comment by airjp73** [comment]
Now that you mention it, I don't think we're handling the `defaultValues` type recursively at all and we should definitely do that.

Supporting null makes sense but there are a couple things that make me wonder about it. The Typescript type for `defaultValue` on an input doesn't support null, but nothing bad happens if you set it to be null. The `value` prop is different though -- you get a console error if you provide null for that.

Not really sure if any of those are dealbreakers.

---

Had some time to play around with an implementation but no time tonight to add it into the library.

[Typescript playground link](https://www.typescriptlang.org/play?#code/PTAEEkFsAcBsFNLwHYBcCGqCWB7ZAofVAT2nlACV4BjAVwCcBnLAN3gDlbZZ0AjBAAr0cZetniMAPABVQ8AB6oUAE0agA3gF8AfKAC8G-KFABtAGJZ4sZaCzJQAa3jEcAM1DSAugH4AXJRoGZjZObj4EAFVkB2QcAHdkGXNLa09dAB9QZC5YUEzaZGV4Vzt4ZQBufE1KolJyKjomVg4c8PgomPjE6V0DWQUlQrVwZEYMZGp4aTrJdGRibSNQbw8l-37FFTUtJZWGoObQnn54IRF4MUspHrWPOU2h0ABBenp0Ykk7VwuIJUhF4wrF5vD77JohVonDqxBKScB-bQA0DrGr4EAeCTYZAAc0I1B4jDUZhwOAAwgTtktXCTyehCWdRCR9KAAER05SuFmVTSEEhkDFjZnqKkk-zC4zGXjoej+Mb0OzYyrGapLKUALz8oDlCqVoBwqAAFhdiThGGKlpLpbLUPKcbrNCZPLrqTgACKYeD+d1KZ00in+E20wncmrUPCCw0K-xg4ItMInBkXcTXTG9DSaUB0zPzUPh1CgJSCgyRnEAOhdQcYAEJy366YxE2JiOUgA)
```ts
type RecursiveNullableProperties<T extends {}> = {
  [Field in keyof T]?: RecursiveNullableUnknown<T[Field]> | null | undefined;
};

type RecursiveNullableUnknown<T> = T extends InstanceType<any>
  ? T
  : T extends {}
  ? RecursiveNullableProperties<T>
  : T extends Array<infer Item>
  ? Array<RecursiveNullableUnknown<Item>>
  : T;
```

**Comment by TheRealFlyingCoder** [comment]
Yeah defaultValues will natively ignore null for obvious reasons, it's just typescript that has a problem with it.

For the library to have no typescript issues you'd have to switch the type back using my recursive null -> undefined to make TS happy when you use the values too.

Technically you don't have to actually alter the object at all, just trick TS... but I guess you could process it? I dunno

**Comment by airjp73** [comment]
I don't think I want to process the object since `null` might actually have some meaning for a controlled component that's backed by a hidden input or something. The `defaultValue` you get from `useField` is already `any` rather than any particular type. I think I'm okay with this being on the developer -- if you pass `null` as the default value, you're going to get `null` as the default value.

**Comment by airjp73** [comment]
Ah, this is trickier than I thought. Typescript can't really distinguish between "an instance of a class" and "a plain object", because technically an object is an instance of a class.

So if it's typed like this, it works with regular objects and arrays, but also makes any class properties and methods optional.

```ts
type RecursiveNullableProperties<T extends {}> = {
  [Field in keyof T]?: RecursiveNullableUnknown<T[Field]> | null | undefined;
};

type RecursiveNullableUnknown<T> = T extends {}
  ? RecursiveNullableProperties<T>
  : T extends Array<infer Item>
  ? Array<RecursiveNullableUnknown<Item>>
  : T;
```

And if we include the `InstanceType` check like the version of the code in my previous comment, then it's effectively not recursive anymore because every object matches that.

The other alternative is to check for specific classes like `Date`, but that sounds messy.

Might still be able to make this work, but I need to keep thinking on it.

**Comment by airjp73** [comment]
I think I may go ahead without checking for class types. The type of `defaultValues` is more of a helpful type hint for autocompletion than anything that gets consumed anywhere, so it should be fine if everything within a `Date` is weirdly nullable in the type.

**Comment by airjp73** [comment]
I'm going to close this for now since it's been around for awhile. I haven't really made time to work out the kinks here because I'm not 100% convinced this change is necessary.
