### ISSUE TITLE
[Feature]: First class support for search params in form action or a custom Form

### ISSUE THREAD

**Issue by arpitdalal** [airjp73/remix-validated-form#84]
### What is the new or updated feature that you are suggesting?

I've a proposal that this library should have first-class support to handle search prams in the form action URL or support providing  custom `Form` component that it can use.
The current behavior is as follows:
1. go to https://id5qm1-3000.sse.codesandbox.io/
2. Click on "Go to route" and that will add ?redirectTo=/ to the URL
3. submit the form, once the result comes back (adds success text), that will remove the ?redirectTo=/ from the URL

Note: the above example doesn't use `ValidatedForm` from this library but it is the same behavior with `ValidatedForm` as well because it just uses vanilla Remix `Form` or `fetcher.Form`

I believe this can be solved in 2 ways:
1. providing an optional `clearSearchParams` prop to `ValidatedForm` whose types are `clearSearchParams?: boolean | string[]; = false`
    - default it's false, meaning it keeps all the `searchParams` coming from `useSearchParams` hook from `remix`
    - if provided `true`, it strips off all the `searchParams` from the `action` URL
    - if provided an array of strings, it will only strip the params that are provided in that array of strings, i.e. if provided ["redirectTo", "foo"], it will only strip off these 2 params and will keep others
2. providing an optional `CustomRemixForm` prop that can take a `RemixForm` type but can have custom implementations made by the developer, of course this `CustomRemixForm`  must forward ref and this `CustomRemixForm` can be used [here](https://github.com/airjp73/remix-validated-form/blob/e824addd25f62a0f95b57cc44666caec41e6ddfa/packages/remix-validated-form/src/ValidatedForm.tsx#L232) like this: `const Form = CustomRemixForm ?? fetcher?.Form ?? RemixForm;` and have to put a check to see if developer is passing both a `fetcher` and a `CustomRemixForm` or not and if yes, throw an error saying "only one of two can be used"

I think allowing developers to provide a `CustomRemixForm` would give them the ability to implement a lot of stuff themselves. Or maybe both of these options can be implemented as well. I came here with a problem of `searchParams` but maybe providing a `CustomRemixForm` can solve other problems too. I'm also open to other ideas or concerns with my proposal. Let me know what you think @airjp73

### Why should this feature be included?

I'm more leaning towards `CustomRemixForm` option because that will give a lot of power into developers' hands and this library only handles the validation part and not worry about the `searchParams`, etc functionality. So to make this library streamlined to validation I think `CustomRemixForm` feature should be implemented.

**Comment by airjp73** [comment]
Could you describe a little more about your use-case and what you're trying to accomplish? Going off the example you provided, I think a more idiomatic way to implement it would be through using a combination of `redirect` and `session.flash`. Here's an [example Codesandbox](https://codesandbox.io/s/charming-colden-ur0o90?file=/app/routes/route.tsx:392-393)

**Comment by airjp73** [comment]
Ah, okay. I see what you mean now! Unfortunately, if the `ValidatedForm` used you custom form component as written, it would break some of the functionality of the library -- the action being passed to the `ValidatedForm` and the actual `form` element need to be the same.

Fortunately, you can still definitely extract this into a re-usable component in exactly the same way you did for the base remix form. Something like [this sandbox](https://codesandbox.io/s/lively-firefly-01s5bh?file=/app/components/Form.tsx).

**Comment by arpitdalal** [comment]
Yes, making a wrapper around the `ValidatedForm` is how I use it right now, but thought it could be a feature built into the lib.
What is the action being used for in `ValidatedForm`? Why would you need to put it in `jotai`?

**Comment by airjp73** [comment]
> What is the action being used for in ValidatedForm? Why would you need to put it in jotai?

Actually, it looks like I'm not using it anymore. It used to get used to detect if the form was being submitted but I refactored to not need it. That's probably worth cleaning up.

> Yes, making a wrapper around the ValidatedForm is how I use it right now, but thought it could be a feature built into the lib.

I think I'm finally up to speed with what you're proposing here. I initially went into problem solving mode because I thought you were saying that your use-case couldn't be solved without api changes to ValidatedForm. Now I understand that you're saying, "It's possible to do this already, but it would be nice if there was an API in ValidatedForm like this."

Could you describe a bit more what the advantage of the propose API is over using a wrapper?

I'm not inherently opposed to allowing this kind of customization, but I don't want to expose implementation details unless there's a strong use-case that can't be solved nicely another way.

I've honestly toyed around with the idea of ditching the remix `Form` component completely since we already re-implement half of it 😆. I don't think I'll do that either unless there's a really good reason for it, but I definitely want to keep my options open. If we support customizing the form component, then we're reducing future options

**Comment by arpitdalal** [comment]
> "It's possible to do this already, but it would be nice if there was an API in ValidatedForm like this."

Exactly what I meant. Actually, I first came here to pitch the idea of including the `clearSearchParams` in this lib but while writing this, I thought that this lib is not for that, instead, it should only do what it is best at and that is validations. So I also included the second option of having a prop `CustomRemixForm` that could make solutions for other problems easier than wrapping the `ValidatedForm` into another component, that just becomes a component soup in my opinion.

About ditching the remix form, why would you want to? Of course, you can implement it from scratch but why do it when there already is an implementation and I think a lot of users of this lib would expect it to use Remix form. So, then this liv would have to implement everything the Remix form can and would do.

About use-cases, there can be many use cases, basically, where ever you want to dynamically generate the value of any prop on `RemixForm` and want to use that form in a lot of places, you can just create your `CustomForm` with generating that dynamic values and passing those off to `RemixForm` and passing the `CustomForm` to this lib which does validations and wouldn't care what Form is underneath even, I could even use an HTML form and call it a day. Using HTML form wouldn't break things, would it? MUI follows this pattern where it lets you pass the component that you want to use for example a `Link` and MUI would only care about styling the component. So, I can pass Remix `Link` to it to use so I get the best of both worlds, the styling of MUI's Link and SPA transitions, prefetch, etc from Remix Link.

I understand if you want to keep options open to do more in the future if you control the component. But maybe you can offer another component different than `ValidatedForm` that does more than just validation and that component might not have an API to swap out the underneath form component so this lib would be in total control of it. Because what if someone doesn't want other features and just care about validation, they can skip the more featured component and just use `ValidatedForm`

I'm not trying to convince you or anything, just exploring options. What do you think @airjp73?

**Comment by airjp73** [comment]
I think the general sentiment of no letting `ValidatedForm` become bloated with too many features is a good one. I don't have any concrete plans right now to split anything out though.

> So I also included the second option of having a prop CustomRemixForm that could make solutions for other problems easier than wrapping the ValidatedForm into another component, that just becomes a component soup in my opinion.

I think this is probably where we differ. I don't see "component soup", I see "yay, win for composition".

Personally, in this situation, I would still make a wrapper component even if this feature existed, it's just that the wrapper would do nothing but pass the custom form component to the `ValidatedForm`. I'd rather have an extra component in my tree than specify a `customForm` prop everywhere I have a form. So we're not really reducing the number of components, we're just moving logic from outside the `ValidatedForm` to inside the `ValidatedForm`, which feels unnecessary to me.

Approaching this type of use-case with _composition_ (I can wrap this component and add my custom behavior) rather than with _configuration_ (I can hook directly into the internals of the component and add my custom behavior) is the type of pattern I'd like to encourage.

I'd also like for `ValidatedForm` to be a bit of a parallel to remix's `Form`. If remix added support for a `customForm` prop, I feel like that would be really unexpected.

Thanks for taking the time to bring this up, though!
